### ISSUE TITLE
ZGY to SEGY converter ; Header is not segyioclassical

### ISSUE THREAD

**Issue by ernygati** [equinor/pyzgy#2]
Hello! I have a few questions regarding pyzgy.
1) Apparently, pyzgy is a wrapper on the segyio, so it doesn't have some usefull methods, like .bin or .text. Where i can find direct converter from zgy to segyio file without using pyzgy to work with siesmic cubes ?
2) Secondly, i discovered that file.header method doesn't outputs metadata of the whole seismic cube, like segyio does. Instead it outputs information of each trace in the cube, which is not helpful. How i can manage this situation?
3) Does pyzgy library have a method 'bin_size' that allow to extract a size of a bin in physical meters?

**Comment by da-wad** [comment]
1. ZGY files do not have bin or text headers.
2. file.header creates objects representing trace headers of the same type as segyio, and to contain information as close as possible to segyio headers within the limits of what ZGY files have for metadata.
3. No, but you can compute this from the CDP_X and CDP_Y trace headers if they exist.
